export { default as LoginRegister } from "./loginRegister/LoginRegister";
export { Page404 } from "./page404/Page404";
export { RestaurantManager } from "./restaurantManager/RestaurantManager";
export { EditProfile } from "./editProfile/EditProfile";
export { ResetPassword } from "./resetPassword/ResetPassword";
export { ForgotPassword } from "./forgotPassword/ForgotPassword";
export { Records } from "./records/Records";
export { default as AccountConfirmation } from "./accountConfirmation/AccountConfirmation";
export { LoginRedirect } from "./loginRedirect/LoginRedirect";
export { ResetConfirmationMail } from "./resetConfirmationMail/ResetConfirmationMail";
export { Profile } from "./profile/Profile";
export { Statistics } from "./statistics/Statistics";
export { Leaderboards } from "./leaderboards/Leaderboards";
